import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <AuthProvider>
          <Container maxWidth={{ md: "80vw" }}>
            <Theme accentColor='purple'>
              <NavBar />
              <main className='p-5'>{children}</main>
              {/* <ThemePanel /> */}
            </Theme>
          </Container>
        </AuthProvider>
      </body>
    </html>
  );
}
