import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import NavBar from "./NavBar";
import QueryClientProvider from "./QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <QueryClientProvider>
          <AuthProvider>
            <Container maxWidth={{ md: "80vw" }}>
              <Theme accentColor='purple'>
                <NavBar />
                <main className='p-5'>{children}</main>
                {/* <ThemePanel /> */}
              </Theme>
            </Container>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
